### PR TITLE
Port #4041 to hyperv-iso builder

### PR DESCRIPTION
**Pull request by PatrickLang**
This fixes https://github.com/taliesins/packer-baseboxes/issues/2 :)

### CODE REVIEW

**Comment by taliesins** [comment]
I guess for now there is not a stable way to get the correct exit code from multiple operating systems.

This was the reason I hacked in the exit code == 1 && len(errout) < 1.

I am gonna give one final go tonight before I push merge button tommorow.

**Comment by taliesins** [comment]
@PatrickLang fix the conflict and I will merge it in

**Comment by PatrickLang** [comment]
Ack, I'll do a rebase. be right back

Actually, it looks like the right change is on top. Is a squash or rebase actually needed?

**Comment by PatrickLang** [comment]
Submitted alternate #11 that has no conflicts, clean history

**Pull request closed without merging**
